using System.ComponentModel.DataAnnotations;

namespace BARQ.Core.Entities
{
    public class Invoice : BaseEntity
    {
        [Required]
        public new Guid TenantId { get; set; }
        
        [Required]
        public Guid SubscriptionId { get; set; }
        
        [Required]
        [MaxLength(50)]
        public string InvoiceNumber { get; set; } = string.Empty;
        
        [Required]
        [MaxLength(20)]
        public string Status { get; set; } = "Draft"; // Draft, Sent, Paid, Overdue, Cancelled, Refunded
        
        [Required]
        public decimal SubtotalAmount { get; set; }
        
        public decimal TaxAmount { get; set; } = 0;
        
        public decimal DiscountAmount { get; set; } = 0;
        
        [Required]
        public decimal TotalAmount { get; set; }
        
        [Required]
        [MaxLength(3)]
        public string Currency { get; set; } = "USD";
        
        [Required]
        public DateTime InvoiceDate { get; set; }
        
        [Required]
        public DateTime DueDate { get; set; }
        
        public DateTime? PaidDate { get; set; }
        
        public DateTime BillingPeriodStart { get; set; }
        
        public DateTime BillingPeriodEnd { get; set; }
        
        [MaxLength(50)]
        public string? StripeInvoiceId { get; set; }
        
        [MaxLength(50)]
        public string? StripePaymentIntentId { get; set; }
        
        [MaxLength(1000)]
        public string? Notes { get; set; }
        
        [MaxLength(2000)]
        public string? Metadata { get; set; } // JSON for additional data
        
        public bool IsAutoGenerated { get; set; } = true;
        
        public int PaymentAttempts { get; set; } = 0;
        
        public DateTime? LastPaymentAttempt { get; set; }
        
        public virtual Tenant Tenant { get; set; } = null!;
        public virtual TenantSubscription Subscription { get; set; } = null!;
        public virtual ICollection<InvoiceLineItem> LineItems { get; set; } = new List<InvoiceLineItem>();
    }
}
