title = "BARQ gitleaks"

[[allowlist]]
description = "Dev/test placeholders in specific files only"
paths = [
  "Backend/src/BARQ.API/appsettings.Development.json",
  "Backend/src/BARQ.API/appsettings.Docker.json",
  "docs/deployment/README.md",
  ".env.example"
]
regexes = [
  "dummy-dev-key",
  "YourStrong@Passw0rd"
]
