title = "BARQ gitleaks"

[allowlist]
description = "Dev/test placeholders"
paths = [
  "Backend/src/BARQ.API/appsettings.Development.json",
  "Backend/src/BARQ.API/appsettings.Docker.json",
  "docs/deployment/README.md",
  ".env.example",
  "docker-compose.yml",
  "Makefile",
  ".github/workflows/api-db-audit.yml",
]
regexes = [
  "dummy-dev-key",
  "YourStrong@Passw0rd",
]
