apiVersion: v1
kind: Secret
metadata:
  name: barq-secrets
  namespace: barq-production
type: Opaque
data:
  ConnectionStrings__DefaultConnection: ""
  JWT__KEY: ""
  JWT__EXPIRYMINUTES: ""
  FILESTORAGE__SIGNINGKEY: ""
  FLOWABLE__BASEURL: ""
