apiVersion: v1
kind: ConfigMap
metadata:
  name: barq-config
  namespace: barq-preview
data:
  ASPNETCORE_ENVIRONMENT: "Preview"
  JWT_ISSUER: "https://api.barq-preview.tetco.sa"
  JWT_AUDIENCE: "barq-users"
  CORS_ALLOWED_ORIGINS: "https://barq-preview.tetco.sa"
  LOGGING__LOGLEVEL__DEFAULT: "Information"
  LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE: "Warning"
  AUTH__COOKIE__ENABLED: "true"
  AUTH__COOKIE__NAME: "__Host-Auth"
  AUTH__COOKIE__PATH: "/"
  AUTH__COOKIE__SECURE: "true"
  AUTH__COOKIE__SAMESITE: "None"
