apiVersion: apps/v1
kind: Deployment
metadata:
  name: barq-api
  namespace: barq-preview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: barq-api
  template:
    metadata:
      labels:
        app: barq-api
    spec:
      containers:
      - name: api
        image: ghcr.io/alsairy/barq-api:{{TAG}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: barq-api-config
        - secretRef:
            name: barq-api-secrets
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: barq-api
  namespace: barq-preview
spec:
  selector:
    app: barq-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
