apiVersion: v1
kind: Secret
metadata:
  name: barq-api-secrets
  namespace: barq-preview
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: ""
  Jwt__Key: ""
  FileStorage__SigningKey: ""
  Flowable__BaseUrl: ""
