name: API & Database Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  api-db-audit:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: YourStrong@Passw0rd
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        pip install requests
        dotnet restore Backend/BARQ.sln
    
    - name: Run Database Migrations
      run: |
        dotnet ef database update --project Backend/src/BARQ.Infrastructure --startup-project Backend/src/BARQ.API
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=BarqDev;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;"
    
    - name: Run API (Dev env on fixed port)
      run: |
        export ASPNETCORE_ENVIRONMENT=Development
        dotnet run --project Backend/src/BARQ.API/BARQ.API.csproj --no-build --urls http://localhost:5080 &
        for i in {1..30}; do
          curl -fsSL http://localhost:5080/health/ready && break
          echo "waiting for API... ($i)"; sleep 2
        done
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=BarqDev;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;"
    
    - name: Create Audit Directory
      run: mkdir -p audit
        
    - name: Extract API Routes
      run: |
        python3 scripts/controller_routes.py Backend/src/BARQ.API/Controllers > audit/controller_routes.json
    
    - name: Probe API Endpoints
      run: |
        python3 scripts/api_probe.py http://localhost:5080 audit/controller_routes.json audit/audit_api.csv
    
    - name: Apply EF migrations (ensures schema exists)
      run: |
        dotnet tool install --global dotnet-ef || true
        export PATH="$PATH:~/.dotnet/tools"
        dotnet ef database update --project Backend/src/BARQ.Infrastructure --startup-project Backend/src/BARQ.API
    
    - name: Run Placeholder Sweep
      run: |
        python3 scripts/placeholder_sweep.py Backend Frontend audit/audit_placeholders.csv || true
    
    - name: Upload Audit Results
      uses: actions/upload-artifact@v4
      with:
        name: api-db-audit-results
        path: |
          audit/audit_api.csv
          audit/audit_db.txt
          audit/audit_placeholders.csv
