name: Deploy BARQ Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'v1.0.0'
        type: string
      canary_weight:
        description: 'Canary traffic weight (10, 50, or 100 for full rollout)'
        required: true
        default: '10'
        type: choice
        options:
        - '10'
        - '50'
        - '100'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: alsairy/barq-api
  IMAGE_NAME_FRONTEND: alsairy/barq-frontend

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for API
      id: meta-api
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          
    - name: Extract metadata for Frontend
      id: meta-frontend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          
    - name: Build and push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Backend/Dockerfile
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: Frontend/barq-frontend
        file: Frontend/barq-frontend/Dockerfile
        push: true
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
        
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        kubectl config current-context
        
    - name: Apply Kubernetes manifests
      run: |
        export KUBECONFIG=kubeconfig
        
        # Apply namespace first
        kubectl apply -f k8s/prod/namespace.yaml
        
        # Apply config and secrets
        kubectl apply -f k8s/prod/api-config.yaml
        kubectl apply -f k8s/prod/api-secrets.yaml
        
        # Patch secrets with actual values
        kubectl patch secret barq-api-secrets -n barq-prod --type='json' -p='[
          {"op": "replace", "path": "/stringData/ConnectionStrings__DefaultConnection", "value": "${{ secrets.SQL_SA_PASSWORD }}"},
          {"op": "replace", "path": "/stringData/Jwt__Key", "value": "${{ secrets.JWT__KEY }}"},
          {"op": "replace", "path": "/stringData/FileStorage__SigningKey", "value": "${{ secrets.FILESTORAGE__SIGNINGKEY }}"},
          {"op": "replace", "path": "/stringData/Flowable__BaseUrl", "value": "${{ secrets.FLOWABLE__BASEURL }}"}
        ]'
        
        # Apply deployments and services
        kubectl apply -f k8s/prod/api-deployment.yaml
        kubectl apply -f k8s/prod/app-deployment.yaml
        
        # Update image tags in deployments
        kubectl set image deployment/barq-api api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}:${{ inputs.tag }} -n barq-prod
        kubectl set image deployment/barq-frontend app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:${{ inputs.tag }} -n barq-prod
        
        # Apply ingress based on canary weight
        if [ "${{ inputs.canary_weight }}" = "100" ]; then
          echo "Full rollout - removing canary ingress"
          kubectl delete -f k8s/prod/api-ingress-canary.yaml --ignore-not-found=true
          kubectl apply -f k8s/prod/api-ingress.yaml
        else
          echo "Canary deployment with ${{ inputs.canary_weight }}% traffic"
          # Update canary weight
          sed 's/nginx.ingress.kubernetes.io\/canary-weight: "10"/nginx.ingress.kubernetes.io\/canary-weight: "${{ inputs.canary_weight }}"/g' k8s/prod/api-ingress-canary.yaml | kubectl apply -f -
          kubectl apply -f k8s/prod/api-ingress.yaml
        fi
        
        kubectl apply -f k8s/prod/app-ingress.yaml
        
    - name: Wait for deployment rollout
      run: |
        export KUBECONFIG=kubeconfig
        kubectl rollout status deployment/barq-api -n barq-prod --timeout=600s
        kubectl rollout status deployment/barq-frontend -n barq-prod --timeout=600s
        
    - name: Verify health endpoints
      run: |
        sleep 30
        for i in {1..10}; do
          if curl -f https://api.barq.tetco.sa/health/ready; then
            echo "API health check passed"
            break
          fi
          echo "Waiting for API to be ready... ($i/10)"
          sleep 30
        done
        
        for i in {1..10}; do
          if curl -f https://barq.tetco.sa/; then
            echo "Frontend health check passed"
            break
          fi
          echo "Waiting for Frontend to be ready... ($i/10)"
          sleep 30
        done
        
    - name: Monitor canary deployment
      if: inputs.canary_weight != '100'
      run: |
        echo "Monitoring canary deployment with ${{ inputs.canary_weight }}% traffic for 5 minutes..."
        for i in {1..10}; do
          echo "Health check $i/10..."
          curl -f https://api.barq.tetco.sa/health/ready || exit 1
          curl -f https://api.barq.tetco.sa/health/flowable || echo "Flowable health check failed"
          curl -f https://api.barq.tetco.sa/health/ai || echo "AI health check failed"
          sleep 30
        done
        echo "Canary monitoring completed successfully"
        
    - name: Run production smoke tests
      run: |
        cd Frontend/barq-frontend
        npm ci
        npx playwright install --with-deps
        PLAYWRIGHT_BASE_URL="https://barq.tetco.sa" npx playwright test tests/wiring.smoke.spec.ts --reporter=line --workers=1
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-production
        path: Frontend/barq-frontend/playwright-report/
        retention-days: 30
        
    - name: Cleanup kubeconfig
      if: always()
      run: rm -f kubeconfig
