name: Functional Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Run Backend Audit
      run: |
        python3 scripts/backend_audit.py --src Backend --out audit_backend.csv --fail-on High
    
    - name: Upload Backend Audit Results
      uses: actions/upload-artifact@v3
      with:
        name: backend-audit-results
        path: audit_backend.csv

  frontend-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm i minimist --prefix scripts --no-save
    
    - name: Run Frontend Audit
      run: |
        node scripts/frontend_audit.js --src Frontend/barq-frontend --out audit_frontend.csv --fail-on High
    
    - name: Upload Frontend Audit Results
      uses: actions/upload-artifact@v3
      with:
        name: frontend-audit-results
        path: audit_frontend.csv
