name: UI Smoke Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ui-smoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Frontend Dependencies
      run: |
        cd Frontend/barq-frontend
        npm ci
    
    - name: Install Playwright
      run: |
        cd Frontend/barq-frontend
        npx playwright install --with-deps
    
    - name: Build Frontend
      run: |
        cd Frontend/barq-frontend
        npm run build
    
    - name: Start Frontend
      run: |
        cd Frontend/barq-frontend
        npm run preview -- --port 4173 &
        sleep 15
        
    - name: Wait for Frontend to be Ready
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:4173; do sleep 1; done'
    
    - name: Run Playwright Smoke Tests
      run: |
        cd Frontend/barq-frontend
        npx playwright test tests/wiring.smoke.spec.ts --reporter=list
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: Frontend/barq-frontend/playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-results
        path: Frontend/barq-frontend/test-results/
        retention-days: 30
